gui:
  theme:
    activeBorderColor:
      - "#cba6f7"
      - bold
    inactiveBorderColor:
      - "#45475a"
    optionsTextColor:
      - "#89b4fa"
    selectedLineBgColor:
      - "#313244"
    selectedRangeBgColor:
      - "#313244"
    cherryPickedCommitBgColor:
      - "#45475a"
    cherryPickedCommitFgColor:
      - "#cba6f7"
    unstagedChangesColor:
      - "#f38ba8"
    defaultFgColor:
      - "#cdd6f4"
    searchingActiveBorderColor:
      - "#f9e2af"
  nerdFontsVersion: "3"
  timeFormat: "02 Jan 06"
  shortTimeFormat: "15:04"
  showFileTree: true
  showRandomTip: false
  showCommandLog: false
  expandFocusedSidePanel: false
  mouseEvents: true

git:
  paging:
    colorArg: always
    pager: delta --dark --paging=never
  commit:
    signOff: true
  branchLogCmd: "git log --graph --color=always --abbrev-commit --decorate --date=relative --pretty=medium {{branchName}} --"
  allBranchesLogCmd: "git log --graph --all --color=always --abbrev-commit --decorate --date=relative --pretty=medium"
  autoFetch: true
  autoRefresh: true
  fetchAll: true

refresher:
  refreshInterval: 10

update:
  method: never

keybinding:
  universal:
    quit: q
    quit-alt1: <c-c>
    return: <esc>
    togglePanel: <tab>
    prevItem: <up>
    nextItem: <down>
    prevBlock: <left>
    nextBlock: <right>
    nextMatch: "n"
    prevMatch: "N"
    startSearch: "/"
    optionMenu: "x"
    scrollUpMain: <pgup>
    scrollDownMain: <pgdown>
    scrollUpMain-alt1: "K"
    scrollDownMain-alt1: "J"
  commits:
    squashDown: s
    renameCommit: r
    renameCommitWithEditor: R
    viewResetOptions: g
    markAsFixup: f
    createFixupCommit: F
    squashAboveCommits: S
    moveDownCommit: <c-j>
    moveUpCommit: <c-k>
    amendToCommit: A
    pickCommit: p
    revertCommit: t
    cherryPickCopy: C
    pasteCommits: V
    tagCommit: T
    checkoutCommit: <space>
    resetCherryPick: <c-R>
    copyCommitAttributeToClipboard: "y"
    openLogMenu: <c-l>
    openInBrowser: o
    viewBisectOptions: b
    interactiveRebase: i
